<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-27T18:16:06 IST" name="Suite" finished-at="2023-05-27T18:16:43 IST" duration-ms="36308">
    <groups>
      <group name="ErrorHandling">
        <method signature="StandAlonePOM2ErrorValidation.loginErrorValidations()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" name="loginErrorValidations" class="rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" name="submitOrder" class="rahulshettyacademy.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-05-27T18:16:06 IST" name="StandAlone E2E" finished-at="2023-05-27T18:16:37 IST" duration-ms="30848">
      <class name="rahulshettyacademy.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:07 IST" name="launchApplication" finished-at="2023-05-27T18:16:19 IST" duration-ms="11812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:19 IST" name="submitOrder" data-provider="getData" finished-at="2023-05-27T18:16:23 IST" duration-ms="4603" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Shumail*786, email=shumailpasha@gmail.com, productName=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:23 IST" name="tearDwon" finished-at="2023-05-27T18:16:23 IST" duration-ms="285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:23 IST" name="launchApplication" finished-at="2023-05-27T18:16:28 IST" duration-ms="4085" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:28 IST" name="submitOrder" data-provider="getData" finished-at="2023-05-27T18:16:31 IST" duration-ms="3858" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Shumail*786, email=danish@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:31 IST" name="tearDwon" finished-at="2023-05-27T18:16:32 IST" duration-ms="617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:32 IST" name="launchApplication" finished-at="2023-05-27T18:16:36 IST" duration-ms="3678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistory()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:36 IST" name="OrderHistory" finished-at="2023-05-27T18:16:36 IST" depends-on-methods="rahulshettyacademy.Tests.SubmitOrderTest.submitOrder" duration-ms="730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.SubmitOrderTest@41709512]" started-at="2023-05-27T18:16:36 IST" name="tearDwon" finished-at="2023-05-27T18:16:37 IST" duration-ms="789" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- rahulshettyacademy.Tests.SubmitOrderTest -->
    </test> <!-- StandAlone E2E -->
    <test started-at="2023-05-27T18:16:06 IST" name="StandAlone error validations" finished-at="2023-05-27T18:16:43 IST" duration-ms="36308">
      <class name="rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:06 IST" name="launchApplication" finished-at="2023-05-27T18:16:19 IST" duration-ms="12151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidations()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:19 IST" name="loginErrorValidations" finished-at="2023-05-27T18:16:20 IST" duration-ms="1379" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation.loginErrorValidations(StandAlonePOM2ErrorValidation.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidations -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:20 IST" name="tearDwon" finished-at="2023-05-27T18:16:20 IST" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:20 IST" name="launchApplication" finished-at="2023-05-27T18:16:24 IST" duration-ms="4179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidations()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:24 IST" name="loginErrorValidations" finished-at="2023-05-27T18:16:26 IST" duration-ms="1385" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation.loginErrorValidations(StandAlonePOM2ErrorValidation.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidations -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:26 IST" name="tearDwon" finished-at="2023-05-27T18:16:26 IST" duration-ms="132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:26 IST" name="launchApplication" finished-at="2023-05-27T18:16:30 IST" duration-ms="3777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidations()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:30 IST" name="productErrorValidations" finished-at="2023-05-27T18:16:42 IST" duration-ms="12240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidations -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation@17aad511]" started-at="2023-05-27T18:16:42 IST" name="tearDwon" finished-at="2023-05-27T18:16:43 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- rahulshettyacademy.Tests.StandAlonePOM2ErrorValidation -->
    </test> <!-- StandAlone error validations -->
  </suite> <!-- Suite -->
</testng-results>
